### ISSUE TITLE
Access pretrained weights and test model with different image size  

### ISSUE THREAD

**Issue by kiashann** [IIGROUP/MANIQA#1]
Hi, how we van access pretrained weights. Is this possible to use image with different sizes for test the model?
Do you prepare any google colab demo for project?
@Shuweis

**Comment by Shuweis** [comment]
Hi, thank you for your attention. We will release the MANIQA weights several days later. For different image size, you can crop 224*224 with multiple times and average the score to get the last result. We will prepare the google colab demo in the future.

**Comment by TianheWu** [comment]
> Hi, how we van access pretrained weights. Is this possible to use image with different sizes for test the model? Do you prepare any google colab demo for project? @Shuweis

Hi，Our code includes the timm library. When you train your code, the timm library automatically loads VIT's pretrained models.

**Comment by kiashann** [comment]
> > Hi, how we van access pretrained weights. Is this possible to use image with different sizes for test the model? Do you prepare any google colab demo for project? @Shuweis
> 
> Hi，Our code includes the timm library. When you train your code, the timm library automatically loads VIT's pretrained models.

I want to use the model for inference without training. Could you please share the weight of the model?

**Comment by TianheWu** [comment]
> > > Hi, how we van access pretrained weights. Is this possible to use image with different sizes for test the model? Do you prepare any google colab demo for project? @Shuweis
> > 
> > 
> > Hi，Our code includes the timm library. When you train your code, the timm library automatically loads VIT's pretrained models.
> 
> I want to use the model for inference without training. Could you please share the weight of the model?

Hi, we have already released the checkpoint. You can use the model for inference PIPAL22 Validation.
Link: https://github.com/IIGROUP/MANIQA/releases/tag/PIPAL22-VALID-CKPT

**Comment by kiashann** [comment]
I can't use [this files](https://github.com/IIGROUP/MANIQA/releases/download/PIPAL22-VALID-CKPT/ckpt_valid) you mentioned above for run inference file. How I can run inference file without training with pretrained weight?
@TianheWu
