### ISSUE TITLE
A question about the performance reported in your paper

### ISSUE THREAD

**Issue by XiaoqiWang** [IIGROUP/MANIQA#10]
Hi, is the performance of the synthetic distortion datasets reported in your paper, e.g. CSIQ, TID2013, and KADID-10K, obtained using the reference image splitting training test set with 80-20% ratio? Or is the splitting done directly on all distorted images.

**Comment by TianheWu** [comment]
Hi! thanks for your question!
Your question is same as https://github.com/IIGROUP/MANIQA/issues/7

We use the reference image splitting training test set with 20-20% ratio.
If we just split all distorted images, the performance will drop a lot.

**Comment by XiaoqiWang** [comment]
OK, thanks for your reply.
