### ISSUE TITLE
Could you provide me dataset

### ISSUE THREAD

**Issue by ledaiduongvnth** [IIGROUP/MANIQA#13]
"train_dis_path": "/mnt/data_16TB/wth22/IQA_dataset/PIPAL/Train_Distort/",
"val_dis_path": "/mnt/data_16TB/wth22/IQA_dataset/PIPAL/Val_Distort/",
"train_txt_file_name": "./data/pipal21_train.txt",
"val_txt_file_name": "./data/pipal21_val.txt",

Please provide dataset!

**Comment by TianheWu** [comment]
The dataset link is in our readme.
