### ISSUE TITLE
about checkpoint file

### ISSUE THREAD

**Issue by 9vivian88** [IIGROUP/MANIQA#14]
你好，训练好的权重方便分享吗？

**Comment by monument-and-sea-all-the-gift** [comment]
> 你好，训练好的权重方便分享吗？

https://github.com/IIGROUP/MANIQA/releases/tag/PIPAL22-VALID-CKPT

**Comment by 9vivian88** [comment]
你好，训练的时候，验证loss一直在下降，目前只有第一轮结果是最好的。为什么会出现这个情况啊。

**Comment by monument-and-sea-all-the-gift** [comment]
> 你好，训练的时候，验证loss一直在下降，目前只有第一轮结果是最好的。为什么会出现这个情况啊。

不知道你说的啥意思，能截张图嘛

**Comment by 9vivian88** [comment]
就是eval_epoch的， SRCC, PLCC值随着epoch增加，值一直在减小。

**Comment by monument-and-sea-all-the-gift** [comment]
> 就是eval_epoch的， SRCC, PLCC值随着epoch增加，值一直在减小。

我还没训练过，感觉他的预训练权重应该就能满足需求了，你用的他说的公开训练集训练嘛，看他的readme，好像就只让训练一轮，也不知道啥原因

**Comment by 9vivian88** [comment]
> > 就是eval_epoch的， SRCC, PLCC值随着epoch增加，值一直在减小。
> 
> 我还没训练过，感觉他的预训练权重应该就能满足需求了，你用的他说的公开训练集训练嘛，看他的readme，好像就只让训练一轮，也不知道啥原因

是用的pipal数据集训练的，batch_size改大了也是一样。没说只训练一轮吧。

**Comment by Stephen0808** [comment]
您好，PIPAL数据集容易出现过拟合问题。我们的比赛经验是，学习率大小和训练epoch数是成反比的，当epoch数过大，会出现较大的drop，这是由于过拟合引起的。所以在训练时我们选择了一个能保证了我们只用训一个epoch就能达到最好的效果的学习率。
