### ISSUE TITLE
some questions about your model

### ISSUE THREAD

**Issue by Danee-wawawa** [IIGROUP/MANIQA#2]
Hi, thank you for your work. When I run the file inference.py your provided, I  have some questions.

1、As shown in the code in the figure below, what does the parameter config.num_avg_val mean, I see that it is set to 1.
2、Can I understand the pred in "pred /= config.num_avg_val" as a score for image quality assessment, and does it range from 0 to 1?
3、Is the model "ckpt_valid" you provided in this URL(https://github.com/IIGROUP/MANIQA/releases/tag/PIPAL22-VALID-CKPT) the final model you trained, or is it just a model that has not been trained yet?
Looking forward for your answer.
![image](https://user-images.githubusercontent.com/24379250/165699398-d908bdc6-9cfc-48aa-a300-b6b8d90cd15e.png)

**Comment by TianheWu** [comment]
> Hi, thank you for your work. When I run the file inference.py your provided, I have some questions.
> 
> 1、As shown in the code in the figure below, what does the parameter config.num_avg_val mean, I see that it is set to 1. 2、Can I understand the pred in "pred /= config.num_avg_val" as a score for image quality assessment, and does it range from 0 to 1? 3、Is the model "ckpt_valid" you provided in this URL(https://github.com/IIGROUP/MANIQA/releases/tag/PIPAL22-VALID-CKPT) the final model you trained, or is it just a model that has not been trained yet? Looking forward for your answer. ![image](https://user-images.githubusercontent.com/24379250/165699398-d908bdc6-9cfc-48aa-a300-b6b8d90cd15e.png)

Hi, thank you for your questions!
I will answer your questions one by one：
1. the parameter config.num_avg_val mean “the number of times to verify this image”. In the competition, we found that when we cropped only once for the image, we got the highest score in the final test . So, in inference.py we set the parameter to 1. But when we do the experiments to valid our model. We randomly croped the validation images 20 times.
2. Yes, the range of final score is range from 0 to 1.
3.  The model "ckpt_valid" I provided is the final model we trained for competition validation.

**Comment by Danee-wawawa** [comment]
> > Hi, thank you for your work. When I run the file inference.py your provided, I have some questions.
> > 1、As shown in the code in the figure below, what does the parameter config.num_avg_val mean, I see that it is set to 1. 2、Can I understand the pred in "pred /= config.num_avg_val" as a score for image quality assessment, and does it range from 0 to 1? 3、Is the model "ckpt_valid" you provided in this URL(https://github.com/IIGROUP/MANIQA/releases/tag/PIPAL22-VALID-CKPT) the final model you trained, or is it just a model that has not been trained yet? Looking forward for your answer. ![image](https://user-images.githubusercontent.com/24379250/165699398-d908bdc6-9cfc-48aa-a300-b6b8d90cd15e.png)
> 
> Hi, thank you for your questions! I will answer your questions one by one：
> 
> 1. the parameter config.num_avg_val mean “the number of times to verify this image”. In the competition, we found that when we cropped only once for the image, we got the highest score in the final test . So, in inference.py we set the parameter to 1. But when we do the experiments to valid our model. We randomly croped the validation images 20 times.
> 2. Yes, the range of final score is range from 0 to 1.
> 3. The model "ckpt_valid" I provided is the final model we trained for competition validation.

Thank you for your answer.^_^
