### ISSUE TITLE
Cannot achieve reported test results using pretrained model

### ISSUE THREAD

**Issue by raresionut1** [IIGROUP/MANIQA#20]
Hello, and congratulations for the paper and winning the NR-IQA track at NTIRE 2022 competition.

I've been trying to replicate the test results for the **NTIRE 2022 test set** that were reported in the paper using your code and the model checkpoint you have provided, but without success.
Running the inference script and uploading the output to codalab server, I've managed to obtain the following results:
**SROCC: 0.65, PLCC: 0.67**

However, looking at the competition's leaderboard, I see that you have obtained
**SROCC: 0.70, PLCC: 0.74**

Is there a discrepancy between the github code / model checkpoint and the final model that you have used in the competition? In case this difference in scores is caused only by the usage of ensembles, can you kindly provide more details about which models you have used in the final ensemble, as well as the ensemble strategy? Thank you!

**Comment by ch-andrei** [comment]
The paper states that the best performance was achieved with MANIQA-E, ensemble model using MANIQA.

Single MANIQA model is reported as 0.667 SROCC, 0.702 PLCC.

**Comment by ch-andrei** [comment]
@raresionut1 kudos for your work

Btw did you try MANIQA with other datasets? TID, KADID...?

**Comment by raresionut1** [comment]
No, not yet. Just on PIPAL

**Comment by ch-andrei** [comment]
If possible, please report here what you find :)

**Comment by TianheWu** [comment]
We use lots of ensemble methods to boost our model and get the leaderboard score.

**Comment by TianheWu** [comment]
@ch-andrei I will release other datasets codes and checkpoints soon!
