### ISSUE TITLE
Are you interested in maintaining the repo?

### ISSUE THREAD

**Issue by nick-konovalchuk** [IIGROUP/MANIQA#21]
The concept of referenceless seems pretty useful. It seems to me, it can find commercial use cases. 
Though, the code might need some refactoring. It would be cool to have cpu-compatible models.
So, are you interested in maintaining the repo? I might make some PR's, but idk if they're even needed

**Comment by TianheWu** [comment]
Yes.

**Comment by TianheWu** [comment]
We can email or have some meeting with zoom.
