### ISSUE TITLE
MSU Video Quality Metrics Benchmark Invitation

### ISSUE THREAD

**Issue by msm1rnov** [IIGROUP/MANIQA#24]
Hello! We kindly invite you to participate in our [video quality metrics benchmark](https://videoprocessing.ai/benchmarks/video-quality-metrics_both.html). You can submit MANIQA to the benchmark, following the submission steps, described [here](https://videoprocessing.ai/benchmarks/video-quality-metrics.html#submit). The dataset distortions refer to compression artifacts on professional and user-generated content. The full dataset is used to measure methods overall performance, so we do not share it to avoid overfitting. Nevertheless, we provided the open part of it (around 1,000 videos) within our paper ["Video compression dataset and benchmark of learning-based video-quality metrics"](https://arxiv.org/abs/2211.12109), accepted to NeurIPS 2022.

**Comment by TianheWu** [comment]
Hi, thanks for inviting! MANIQA is the metric of image. I don't know whether it can valid the video quality.

**Comment by msm1rnov** [comment]
Thank you for your answer! Our benchmark includes both VQA and IQA methods. [The participants page](https://videoprocessing.ai/benchmarks/video-quality-metrics_participants.html) shows the type of each method. Image quality metrics are calculated for each frame independently. Then obtained scores are averaged throughout the whole video. Even such a simple temporal pooling strategy sometimes leads to correlation higher than that of video quality metrics (method UNIQUE as a great example).

**Comment by TianheWu** [comment]
Thanks！I will have a look!

**Comment by dmumtaz** [comment]
Hi
Did you try it as a video quality metric?
Please share the code.

**Comment by TianheWu** [comment]
@dmumtaz Not yet, I did some other researches previous. In the future, I will try it as a video quality metric！
