### ISSUE TITLE
a question about released checkpoint

### ISSUE THREAD

**Issue by YaoShunyu19** [IIGROUP/MANIQA#25]
Hi!
In Table 3 of the paper, MANIQA-s achieves 0.686/0.707 on the validation set, and 0.667/0.702 on the test set. Are these two sets of results are obtained from testing the same model checkpoint?
I tried to test and submit using the checkpoint and test script you released, and achieved 0.69/0.71 on the validation set but only 0.66/0.68 on the test set. So I want to know if the results are tested from the same parameters.
Thanks!

**Comment by TianheWu** [comment]
The test sets results are obtained from the ensemble-model.

**Comment by TianheWu** [comment]
@YaoShunyu19 I will release other datasets checkpoints!
