### ISSUE TITLE
code for other datasets?

### ISSUE THREAD

**Issue by BarCodeReader** [IIGROUP/MANIQA#27]
Hi,

Thanks for your code.
Do you mind sharing the code for other datasets like KONIQ, TID2013 etc.?
Because we cannot reproduce the performance you reported in the paper.

Thanks

**Comment by TianheWu** [comment]
Hi, in our process.py file, we split the dataset for training and teseting. It is important to split the data by conent.

**Comment by TianheWu** [comment]
Yes, due to some reasons, I can not share other datasets code. But now, I will release these code and checkpoints！
