### ISSUE TITLE
Issue about the checkpoint

### ISSUE THREAD

**Issue by MartinXM** [IIGROUP/MANIQA#29]
Hi there, as the provided checkpoint contains the whole model rather than the weight parameters, I try to save weight parameters by myself to pytorch_model.pt, and use it as follows: 

model = MANIQA()
model = load_state_dict(torch.load('pytorch_model.pt'))

However, I found the output result is different from your provided model:

net = torch.load('ckpt_valid.ckpt')

I have checked the parameter size, these two models seem to be the same. 

Is there any difference in the forward pass of give model python files and provided checkpoints?

**Comment by TianheWu** [comment]
![image](https://user-images.githubusercontent.com/63295426/223307578-0b1f1d1e-bc17-4af4-8767-57f8ca824054.png)
you can save ckpt like this way.

**Comment by MartinXM** [comment]
Thanks for your reply, I found the problem is in scale=0.8 for MANIQA, it should be 0.13 for PIPAL22 pre-trained model.
