### ISSUE TITLE
hard to get a checkpoint with high srcc and plcc

### ISSUE THREAD

**Issue by YaoShunyu19** [IIGROUP/MANIQA#3]
您好！很高兴看到您们的工作，在运行了您的train_maniqa后，我有几点疑问，期待能得到解答。
我们使用了您的程序中的超参数，除增加了val_freq之外完全相同，训练出的checkpoint在NTIRE2022上提交的结果和paper中的数据以及release的checkpoint相比有一定的差距。我们训练出的checkpoint在pipal_val.txt的结果为：plcc=0.667,srcc=0.691，在NTIRE2022 NRIQA验证集上的结果为：plcc=0.67,srcc=0.65。请问关于这种情况您有什么建议吗？

**Comment by TianheWu** [comment]
您好，我们当时在比赛中也遇到了这样的问题。首先明确一点，pipal_val中是21年PIPAL的验证集，NTIRE2022的验证集和21年是不同的。

我们建议可以考虑**参数初始化**（由于时间关系我们并没有加入代码中）。我们的结果是调了非常多的参数（包括选择随机数种子），最后在短时间内找到了一个较高的结果。数值的波动也可能与模型训练所用的GPU有关，这个我们也做过测试。

**Comment by YaoShunyu19** [comment]
感谢您的建议！请问方便分享每个模块具体用的是什么初始化方法吗？

**Comment by TianheWu** [comment]
> 

可以看看知乎之类的，init_weight用法等
