### ISSUE TITLE
关于推理出的score的含义

### ISSUE THREAD

**Issue by Zuikke** [IIGROUP/MANIQA#30]
感谢作者的开源！我最近初步接触IQA方向，因此想问下对失真图片推理出的score的含义具体代表什么？数值大小代表图片质量高低吗？我试了你们公布的权重，貌似每次推理出的score都是0.01量级的小数？

**Comment by TianheWu** [comment]
MANIQA是用来评估图像质量好坏的指标。这里的好坏指的是符合人类视觉感知的好坏，主要是以失真程度来作为评估的。分数越高，代表图片质量越好。
