### ISSUE TITLE
some question for model architecture

### ISSUE THREAD

**Issue by WFLiu0327** [IIGROUP/MANIQA#37]
In the MANIQA.py file, 
def extract_feature(self, save_output):
        x6 = save_output.outputs[6][:, 1:]
        x7 = save_output.outputs[7][:, 1:]
        x8 = save_output.outputs[8][:, 1:]
        x9 = save_output.outputs[9][:, 1:]
you are using the output of 6, 7, 8 and 9 Blocks in VIT, why did you choose the output of these Blocks?

**Comment by TianheWu** [comment]
At that time, when playing the competition, we tested the output of different stages and found that these stages worked well.

Now, I think these middle stage contain low-level details and high-level semantic information which are the two important factors for IQA.

**Comment by WFLiu0327** [comment]
I see. Thank you for your reply.
