### ISSUE TITLE
MLP RATIO

### ISSUE THREAD

**Issue by KarenAssaraf** [IIGROUP/MANIQA#38]
Hi!
Thank you for the amazing job!
I have tried finetuning and things work somoothly :)

One thing I removed is the argument `mlp_ratio`.
It caused an error when training from koniq10k checkpoint.

in swin.py file, mlp_ratio argument is used thourgh `self.mlp_ratio` but is never iniialized with self.mlp_ratio = mlp_ratio .
What is the utility of this argument exactly?
Is it set to one?

Thanks!

**Comment by TianheWu** [comment]
It set to 1. Thanks!
