### ISSUE TITLE
scale config when using konIQ10k checkpoint

### ISSUE THREAD

**Issue by KarenAssaraf** [IIGROUP/MANIQA#41]
Hi!

I wanted to know what is the scale to use (for SSTB) when using checkpoint form KonIQ10k. Thanks!
In the paper it is mentioned 0.1, in the code it's 0.8, so just want to confirm.

Thanks a lot!

**Comment by TianheWu** [comment]
0.8

**Comment by KarenAssaraf** [comment]
Thanks a lot!
