### ISSUE TITLE
Question for train the model on koniq

### ISSUE THREAD

**Issue by cyclopssssss** [IIGROUP/MANIQA#42]
Hi! use your source code of koniq checkpoint to train, but the plcc/srcc result is lower than yours 
![7ZQ4G{U9G4XAAC4)PK {QTJ](https://github.com/IIGROUP/MANIQA/assets/50789512/6d63137c-c900-4579-9667-249c0416eef5)
how to train the model?

**Comment by TianheWu** [comment]
resize the input image to 224x224 and train

**Comment by TianheWu** [comment]
not crop

**Comment by cyclopssssss** [comment]
thanks so much for your reply~

**Comment by cyclopssssss** [comment]
> not crop

thanks so much for your reply~

**Comment by cyclopssssss** [comment]
but in the code of koniq dataset, resize is already done
![B8FX5V1V~T)QH42MDB732UK](https://github.com/IIGROUP/MANIQA/assets/50789512/ccdb6804-9f59-42a8-89ab-5a96347be64d)
and in that case the crop will do nothing with the img
![JGTRE` PJ2OPH{1S3` ZM`X](https://github.com/IIGROUP/MANIQA/assets/50789512/f2946feb-1f53-41e5-af1a-b13ca4892873)
Any other advice about training?
Thanks again for your patience!

**Comment by TianheWu** [comment]
Thanks! This result is within the acceptable fluctuation range. You can try to change the split seed to see if there are other results.

**Comment by cyclopssssss** [comment]
Got it and sincere thank for you!
