### ISSUE TITLE
About time efficiency of predicting one image

### ISSUE THREAD

**Issue by MeilingLiu1997** [IIGROUP/MANIQA#44]
Hi,

Glad to see the fabulous work! 👏 However, I've not found any data about time cost of assessment an image in the paper. I'm curious about the model performance----How fast the model will get the results? Would your team provide any cpu/gpu cost with different types of cpu/gpu? Several popular devices are enough. 

Perhaps, your team is more focus on the accuracy? Please Let me know if you're interested.

**Comment by MeilingLiu1997** [comment]
btw, 6 core cpu (mine is Intel UHD Graphics 630 1536 MB, this mac seems like not easily support neither cuda nor mps)
I got below:
(3, 310, 542)
100%|███████████████████████████████████████████| 20/20 [00:25<00:00,  1.29s/it]
Applying to 10 of cpu threads, is this the best performance for this mac?

**Comment by TianheWu** [comment]
Hi, thanks for your attention about our work.
Actually, it is my first academic work in my master degree. It's not done perfectly. We focus more on the accuracy. The infernece time will cost about 30min to test about 2000 images (512x512) with 1 V100 GPU.

**Comment by MeilingLiu1997** [comment]
thanks~
