### ISSUE TITLE
训练数据集的问题

### ISSUE THREAD

**Issue by sky-whs** [IIGROUP/MANIQA#5]
请问PIPAL的训练集要在哪里下载呢。
作者您能公布一下训练其他数据集的代码吗？比如TID2013或者LIVE的。
谢谢

**Comment by TianheWu** [comment]
这个自己写一个data file就可以了。
我们已经在process里公开划分各个live，csiq等其余数据集的代码了

**Comment by TianheWu** [comment]
其他训练集的代码，我会陆续公开。之前一直在忙别的科研，以及内部有一些研究需要用到，当时不太方便公开。不过现在已经可以release了！

**Comment by TianheWu** [comment]
@sky-whs
