### ISSUE TITLE
about pipal21_val.txt

### ISSUE THREAD

**Issue by linkboyx** [IIGROUP/MANIQA#6]
hello, I see that pipal21_val.txt in your repo,
but in NTIRE21, the competition does not release the MOS label of the validation set.
so where do you get the label from?  :)
Thank you for sharing your code,  nice work~

**Comment by Shuweis** [comment]
We get the label from the organizers. You can connect with them for the validation label.

**Comment by linkboyx** [comment]
> 

Thanks for your reply~
